-- MySQL Script generated by MySQL Workbench
-- Thu May 24 23:48:21 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Ventes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ventes` (
  `id_vente` INT NOT NULL,
  PRIMARY KEY (`id_vente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Temps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Temps` (
  `id_temps` INT NOT NULL,
  `Ventes_id_vente` INT NOT NULL,
  PRIMARY KEY (`id_temps`, `Ventes_id_vente`),
  INDEX `fk_Temps_Ventes1_idx` (`Ventes_id_vente` ASC),
  CONSTRAINT `fk_Temps_Ventes1`
    FOREIGN KEY (`Ventes_id_vente`)
    REFERENCES `mydb`.`Ventes` (`id_vente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mois`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mois` (
  `id_mois` INT NOT NULL,
  `nom_mois` VARCHAR(45) NULL,
  `Temps_id_temps` INT NOT NULL,
  PRIMARY KEY (`id_mois`, `Temps_id_temps`),
  INDEX `fk_Mois_Temps1_idx` (`Temps_id_temps` ASC),
  CONSTRAINT `fk_Mois_Temps1`
    FOREIGN KEY (`Temps_id_temps`)
    REFERENCES `mydb`.`Temps` (`id_temps`)
    ON DELETE CASCADE
    ON UPDATE CASCADE )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Anneé`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Anneé` (
  `id_anneé` INT NOT NULL,
  `nom_anneé` VARCHAR(45) NULL,
  `Mois_id_mois` INT NOT NULL,
  PRIMARY KEY (`id_anneé`, `Mois_id_mois`),
  INDEX `fk_Anneé_Mois_idx` (`Mois_id_mois` ASC),
  CONSTRAINT `fk_Anneé_Mois`
    FOREIGN KEY (`Mois_id_mois`)
    REFERENCES `mydb`.`Mois` (`id_mois`)
    ON DELETE CASCADE
    ON UPDATE CASCADE )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ville`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ville` (
  `id_ville` INT NOT NULL,
  `nom_vile` VARCHAR(45) NULL,
  `Ventes_id_vente` INT NOT NULL,
  PRIMARY KEY (`id_ville`, `Ventes_id_vente`),
  INDEX `fk_Ville_Ventes1_idx` (`Ventes_id_vente` ASC),
  CONSTRAINT `fk_Ville_Ventes1`
    FOREIGN KEY (`Ventes_id_vente`)
    REFERENCES `mydb`.`Ventes` (`id_vente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Departement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Departement` (
  `id_departement` INT NOT NULL,
  `nom_departement` VARCHAR(45) NULL,
  `Ville_id_ville` INT NOT NULL,
  PRIMARY KEY (`id_departement`, `Ville_id_ville`),
  INDEX `fk_Departement_Ville1_idx` (`Ville_id_ville` ASC),
  CONSTRAINT `fk_Departement_Ville1`
    FOREIGN KEY (`Ville_id_ville`)
    REFERENCES `mydb`.`Ville` (`id_ville`)
    ON DELETE CASCADE
    ON UPDATE CASCADE )
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
