-- MySQL Script generated by MySQL Workbench
-- Thu May 24 23:48:21 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;


-- -----------------------------------------------------
-- Table `mydb`.`Anneé`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Anneé` (
  `id_anneé` INT NOT NULL,
  `nom_anneé` VARCHAR(45) NULL,
  PRIMARY KEY (`id_anneé`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mois`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mois` (
  `id_mois` INT NOT NULL,
  `nom_mois` VARCHAR(45) NULL,
  `id_anneé` INT NOT NULL,
  PRIMARY KEY (`id_mois`),
  CONSTRAINT `fk_Mois_Annee`
    FOREIGN KEY (`id_anneé`)
    REFERENCES `mydb`.`Anneé` (`id_anneé`)
    ON DELETE CASCADE
    ON UPDATE CASCADE 
  )
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `mydb`.`Ville`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ville` (
  `id_ville` INT NOT NULL,
  `nom_vile` VARCHAR(45) NULL,
  PRIMARY KEY (`id_ville`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Departement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Departement` (
  `id_departement` INT NOT NULL,
  `nom_departement` VARCHAR(45) NULL,
  `id_ville` INT NOT NULL,
  PRIMARY KEY (`id_departement`),
    CONSTRAINT `fk_Departement_Ville1`
    FOREIGN KEY (`id_ville`)
    REFERENCES `mydb`.`Ville` (`id_ville`)
    ON DELETE CASCADE
    ON UPDATE CASCADE )
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Ventes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ventes` (
  `nombre_de_ventes` INT NOT NULL,
  `id_mois` INT NOT NULL,
  `id_departement` INT NOT NULL,
  PRIMARY KEY (`id_mois`,`id_departement`),
  CONSTRAINT `fk_Ventes_Mois`
    FOREIGN KEY (`id_mois`)
    REFERENCES `mydb`.`Mois` (`id_mois`)
    ON DELETE CASCADE
    ON UPDATE CASCADE )
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
